Handle build error AttributeError: module 'jinja2' has no attribute 'contextfilter' https://forums.docker.com/t/jinja-mkdocs-issue-breaks-docker101tutorial/122671